config/routes.rb
Rails.application.routes.draw do
  resources :brands
  devise_for :users, path_prefix: 'admin'

  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pantries#index'
  resources :purchases do
    post :add_product, to: 'purchases#add_product'
    member do
      get :products, to: 'purchases#products'
    end
  end
  resources :pantries do
    member do
      get :purchases, to: 'pantries#purchases'
    end
  end
  resources :products
  resources :categories
  resources :users
  resources :roles
  resources :permissions
  resources :tags
end

app/models/pantry.rb
# == Schema Information
#
# Table name: pantries
#
#  id         :bigint           not null, primary key
#  name       :string
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_pantries_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Pantry < ApplicationRecord
  belongs_to :user
  enum status: { inactive: 0, active: 1 }
  has_many :purchases
end

app/controllers/pantries_controller.rb
class PantriesController < ApplicationController
  before_action :set_pantry, only: %i[ show edit update destroy ]

  # GET /pantries or /pantries.json
  def index
    @pantries = Pantry.all
  end

  # GET /pantries/1 or /pantries/1.json
  def show
  end

  # GET /pantries/new
  def new
    @pantry = Pantry.new
  end

  # GET /pantries/1/edit
  def edit
  end

  # POST /pantries or /pantries.json
  def create
    @pantry = Pantry.new(pantry_params)

    respond_to do |format|
      if @pantry.save
        format.html { redirect_to pantries_path, notice: "Pantry was successfully created." }
        format.json { render :show, status: :created, location: @pantry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pantries/1 or /pantries/1.json
  def update
    respond_to do |format|
      if @pantry.update(pantry_params)
        format.html { redirect_to pantry_url(@pantry), notice: "Pantry was successfully updated." }
        format.json { render :show, status: :ok, location: @pantry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pantries/1 or /pantries/1.json
  def destroy
    @pantry.destroy!

    respond_to do |format|
      format.html { redirect_to pantries_url, notice: "Pantry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def purchases
    @pantry = Pantry.find(params[:id])
    @purchases = @pantry.purchases
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pantry
      @pantry = Pantry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pantry_params
      params.require(:pantry).permit(:user_id, :name, :status)
    end
end

app/helpers/pantries_helper.rb
module PantriesHelper
end

app/views/pantries/_form.html.erb
<%= form_with(model: pantry, class: "contents") do |form| %>
  <% if pantry.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(pantry.errors.count, "error") %> prohibited this pantry from being saved:</h2>

      <ul>
        <% pantry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status, Pantry.statuses.keys, {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/pantries/_pantry.html.erb
<div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
  <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= link_to pantry.name, pantry %></h5>

  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
    <strong class="block font-medium mb-1">User:</strong>
    <%= pantry.user_id %>
  </p>

  <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= pantry.status %>
  </p>

  <% if action_name != "show" %>
    <div class="flex mt-4">
      <%= link_to pantry, class: "flex-1 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
        <span>Show</span>
        <svg class="w-4 h-4 ms-2" aria-hidden="true" fill="none" viewBox="0 0 14 10" xmlns="http://www.w3.org/2000/svg">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      <% end %>

      <%= link_to edit_pantry_path(pantry), class: "flex-1 ml-2 inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
        <span>Edit</span>
        <svg class="w-4 h-4 ms-2" aria-hidden="true" fill="none" viewBox="0 0 14 10" xmlns="http://www.w3.org/2000/svg">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pantries/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing pantry</h1>

  <%= render "form", pantry: @pantry %>

  <%= link_to "Show this pantry", @pantry, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to pantries", pantries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pantries/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Alacenas</h1>
    <!-- Modal toggle -->
    <div class="flex justify-center m-5">
      <button id="defaultModalButton" data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="block text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
        Nueva Alacena
      </button>
    </div>
  </div>

<!--  <div id="pantries" class="flex min-w-full gap-3 flex-wrap mt-5">-->
    <%#= render @pantries %>
<!--  </div>-->

  <div class="relative overflow-x-auto shadow-md sm:rounded-lg py-5">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          Alacenas
        </th>
        <th scope="col" class="px-6 py-3">
          Estado
        </th>
        <th scope="col" class="px-6 py-3">
          Owner
        </th>
        <th scope="col" class="px-6 py-3">
          Categoria
        </th>
        <th scope="col" class="px-6 py-3">
          Action
        </th>
      </tr>
      </thead>
      <tbody>
      <% @pantries.each do |pantry| %>
        <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <%= pantry.name %>
          </th>
          <td class="px-6 py-4">
            <%= pantry.status %>
          </td>
          <td class="px-6 py-4">
            <%= pantry.user.full_name %>
          </td>
          <td class="px-6 py-4">
            <%= pantry.status %>
          </td>
          <td class="flex space-x-4 px-6 py-4">
            <%= link_to edit_pantry_path(pantry), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" do %>
              <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.3 4.8 2.9 2.9M7 7H4a1 1 0 0 0-1 1v10c0 .6.4 1 1 1h11c.6 0 1-.4 1-1v-4.5m2.4-10a2 2 0 0 1 0 3l-6.8 6.8L8 14l.7-3.6 6.9-6.8a2 2 0 0 1 2.8 0Z"/>
              </svg>
            <% end %>

            <%= link_to purchases_pantry_path(pantry), class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" do %>
              <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 10V6a3 3 0 0 1 3-3v0a3 3 0 0 1 3 3v4m3-2 1 12c0 .5-.5 1-1 1H6a1 1 0 0 1-1-1L6 8h12Z"/>
              </svg>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>



<%= render 'pantries/modals/pantry' %>

app/views/pantries/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New pantry</h1>

  <%= render "form", pantry: @pantry %>

  <%= link_to "Back to pantries", pantries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/pantries/purchases.html.erb
<div class="flex justify-between items-center">
  <%= link_to pantries_path, class: "flex items-center mr-8 text-gray-500 transition-colors duration-200 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white mb-5" do %>
    <%= tag.svg class: "w-3.5 h-3.5 mr-2", aria_hidden: true, xmlns: "http://www.w3.org/2000/svg", fill: "none", viewBox: "0 0 14 10" do %>
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"></path>
    <% end %>
    Return
  <% end %>
  <h1 class="font-bold text-2xl">Compras</h1>
  <!-- Modal toggle -->
  <div class="flex justify-center m-5">
    <button id="defaultModalButton" data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="block text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" type="button">
      Nueva compra
    </button>
  </div>
</div>

<div class="flex gap-3">
  <% @purchases.each do |purchase| %>
    <div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 flex-item">
      <a href="#">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= purchase.name %></h5>
      </a>
  <!--    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>-->
      <%= link_to products_purchase_path(purchase), class: "inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
        <%= "Visitar" %>
        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
      <% end %>

      <span class="mr-0 inline-flex items-center px-3 py-2 mt-2 text-sm font-medium text-center text-gray-700 bg-gray-100 rounded-lg dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600 dark:focus:ring-gray-800">
        <svg class="w-4 h-4 mr-2" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM9 9a1 1 0 112 0v3a1 1 0 11-2 0V9zm1-5a1 1 0 100 2 1 1 0 000-2z"/>
        </svg>
        <%= distance_of_time_in_words_to_now(purchase.created_at) %>
      </span>
    </div>
  <% end %>
</div>

<%= render 'purchases/modals/purchase' %>

app/views/pantries/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pantry %>

    <%= link_to "Edit this pantry", edit_pantry_path(@pantry), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this pantry", pantry_path(@pantry), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to pantries", pantries_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>